### ISSUE TITLE
replace entities folder with rcpch-census-platform

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#1]
The RCPCH Census Platform returns an RCPCH standardised list of organisations and relationships with their organisational regions. Currently these models are in the entities folder but can be replaced by pulling the relevant information from RCPCH-Census-Platform. This will involve
- [x] remove PDU and Organisation relationship from the Site model and replace with the PDU pz_code and Organisation ODS code
- [ ] add RCPCH Census Platform URL / credentials to .env and settings.py
- [ ] tests to allow correct organisations and organisational regions to be pulled from RCPCH-Census-Platform
- [ ] update documentation with above

**Comment by mbarton** [comment]
We now get this data from https://github.com/rcpch/rcpch-nhs-organisations
