### ISSUE TITLE
Organisations API url should go in .env file

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#101]
Small one - the organisations api url should come from .env file

![Image](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/68898006/38e209f8-d85b-4984-9e14-6d9f62ebddfe)

**Comment by eatyourpeas** [comment]
Sorry @anchit-chandran you are quite right - it is in there already actually but I have been struggling with the api itself and had to delete the service and rebuild it today so now you need to add `RCPCH_NHS_ORGANISATIONS_URL="https://api.rcpch.ac.uk/nhs-organisations/v1"` to your .env and and refactor anywhere it is hardcoded. It is already there in `settings.py` 
It is fine to post here as there are no credentials involved and the service is currently unmetered

**Comment by mbarton** [comment]
This is done now
