### ISSUE TITLE
Pre-fill all login fields for local development

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#102]
Having to keep typing in fields / even pre-filling is tedious for local development!

Pre fill these fields, don't require captch if `settings.DEBUG` is True

**Comment by mbarton** [comment]
Have we checked the django secret is set? If it is you shouldn't have to log in again on each restart which is the most annoying thing

**Comment by anchit-chandran** [comment]
closing as done in PR
