### ISSUE TITLE
Password Reset page styling

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#105]
<img width="630" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/199e4bdb-7061-43c9-a908-3227618acec6">

When a new user is created and they must set their first password this is the page that opens. Styling should should be improved for cleaner ui

**Comment by mbarton** [comment]
> Styling should should be improved for cleaner ui

@dc2007git could you expand on that a bit more? :) I definitely think the text boxes should be more prominently highlighted

**Comment by dc2007git** [comment]
@mbarton sure! We should ideally keep the theme consistent with all the form fields across NPDA. So the password boxes above should simply become `rcpch-input-text` fields, and then centered in the page.

It would also look a bit nicer if the password creation assistant text at the bottom had a small margin top to separate it from the button above
