### ISSUE TITLE
User information not being updated upon saving

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#106]
<img width="919" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/2d34460e-ac88-4c81-9da5-5bdec4b26e26">

When editing a user's information, changing a field, such as 'Employing organisation', and pressing the save 'Edit NPDA User Details' button, the updated information is not persisted and saved, such that upon loading up the User List, the old information is still there, and clicking on the User to see their information also shows the old information.

**Comment by dc2007git** [comment]
Additionally, changing the organisation manually in the admin dashboard does not persist into the application. The test test user as above was previously part of KCH, and I went into the admin dashboard to change them to Queen's Hospital (RJ614), but this does not load in the form. In fact, the form actually says he is now part of Addenbrooke's:
<img width="841" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/c6d7f084-406c-48ba-b692-4e88e1fc99bd">

while the information for test test in the dashboard is as follows:

<img width="1469" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/00a5a321-520b-4b0d-83a1-203128a044a5">

so RJ614 IS persisted in this dashboard, and in admin, but not in the actual Update form. Additionally, PZ215 persists for this user who is, as per the Admin dashboard, part of Queen's hospital, whereas PZ215 is the PDU of King's College Hospital

**Comment by mbarton** [comment]
This seems to work now, although the UI does not allow you to remove an organisation.

@dc2007git please do reopen if you can reproduce or disagree that we should close this
