### ISSUE TITLE
kpi dashboard

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#11]
Each child has multiple visits and these are seen in the 'patient_visits` table.

Below this needs to be a summary (probably a table) of that child's compliance with audit measures.
Currently the Netsolve platform have a table with ticks and crosses for measures completed or failed.
We should use the same methodology from E12:
0 - fail
1 - pass
2 - ineligible
None - unscored
This lends itself to aggregation queries later on

**Comment by anchit-chandran** [comment]
Will close this as #386 exists
