### ISSUE TITLE
Permissions in not correlated to permissions in code

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#114]
In the documentation, we specify the permissions that each user type should be granted:

<img width="513" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/72e99bd6-4f9e-402c-80f3-3dc97dd95b67">

Here we can see that a clinician should NOT be able to delete a Patient instance. However, in the code for the permissions, a clinician has TRUST_AUDIT_TEAM_EDIT_ACCESS permissions, which means they have EDITOR_PERMISSIONS, which means they have the delete_patient permission.

It seems like there is the same discrepancy between the docs and code for deletion permissions for Site and Visit also, for the type clinician. Additionally, for Change, Delete, and Add Site, a clinician would have access to these as per the permissions in the code, whereas the docs say this should not be the case:

<img width="623" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/557faff3-8dd0-4ff5-9d60-dcc412fe016d">

@eatyourpeas should we perhaps go over the permissions together? If the table is the ground truth then i'm happy to implement this in the code, or vice versa?

**Comment by eatyourpeas** [comment]
Yes let's go through it on thursday. I don't think editor access means you can delete things.

**Comment by mbarton** [comment]
`delete_patient` is now only for the RCPCH Audit Team group
