### ISSUE TITLE
IntegrityError - trying to set a field to Null but Django not allowing it

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#115]
In the New Patient form, upon submission, an IntegrityError gets raised as below:

<img width="1253" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/a5d27c87-885c-48ef-9403-b747ad3e3dc5">

This is because in the model, we have not set null=True, because we want every patient to have a site attached. However it seems like this functionality is not working.

I do seem to recall however being able to manually add patients to the platform. @eatyourpeas , could this be due to the Migration changes we made a while back, in PR #87 ? To the best of my knowledge, the last time we made changes to the models/migrations was here.

**Comment by eatyourpeas** [comment]
i would start by creating a fresh instance of the database etc - it may just be that.

**Comment by dc2007git** [comment]
Thanks for fixing this @eatyourpeas ! You'll have to walk me through how in the sprint ;)
