### ISSUE TITLE
Tooltips in Patient and Submission tables

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#117]
<img width="1111" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/a8174efe-64b2-427a-8246-8e2aebf1614f">

For the column headings above where the definition is not immediately obvious, it could be nice to have a small tooltip defining them - in both the cohorts and patients view tables.

So for AUDIT YEAR (QUARTERLY COHORT), something like "An audit runs from 01/04 to 31/03 of the following year. The quarterly cohort is which quarter of that year the submission date of the patient lies in."

**Comment by mbarton** [comment]
I think Audit Cohort should be a top level "submission" filter alongside the PDU. Agree on putting the dates somewhere prominent.

**Comment by mbarton** [comment]
The column now says "Audit Year" which is self explanatory
