### ISSUE TITLE
UI change - error rendering in Visit form

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#123]
[after dev team discussion]

- [x] 1. When a user is looking at the Visit List view for a patient, it is clear where the errors are, and hovering over the red tabs for the erroneous categories shows the error message. Persisting these error messages somewhere into the form would be very helpful for the user to know what is wrong with the current state of the visit.

- [x] 2. The errors do present themselves, but only on form submission. So if the user goes onto the form, the error messages are not present, and they would have to submit the erroneous form again for the errors to pop up.

- [x] 3. When the errors do pop up as described in point 2, they are not formatted well. Tidying them up to make them inline would be nicer.

- [x] 4. Additionally, it isn't [totally] obvious that there are tooltips over the errors which contain the exact error messages. It might be nice to have a 'Hover for Error message' text in the column header:

<img width="845" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/407294d4-32cc-4455-bebf-7e1bdd7e6032">

**Comment by dc2007git** [comment]
Additionally:
<img width="543" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/e4f076f4-1293-458e-8f40-0a2c685ad6ef">

In this visit, routine measurements does have errors, but because it is the selected tab, it turns pink for some reason. Also needs fixing

**Comment by dc2007git** [comment]
> Additionally: <img alt="image" width="543" src="https://private-user-images.githubusercontent.com/65614251/340364425-e4f076f4-1293-458e-8f40-0a2c685ad6ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjI2NzgsIm5iZiI6MTcxOTIyMjM3OCwicGF0aCI6Ii82NTYxNDI1MS8zNDAzNjQ0MjUtZTRmMDc2ZjQtMTI5My00NThlLThmNDAtMGEyYzY4NWFkNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA5NDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTc5MTAzMTFjNjZhNmIxYjBhNGQ4NDRjNjVlMjg2MWM3NWUyNDE0ZDRmYTc4ZTdmZjBhM2Q3MmFlMjUwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OkpXtIpcwNGkNnvRB3K7-lADp40ZDHqV91LKglbCkFU">
> 
> In this visit, routine measurements does have errors, but because it is the selected tab, it turns pink for some reason. Also needs fixing

For this particular problem, it seems that adding a build step for tailwind could solve it.

Apparently, even though in the html we set the background colour of the 'Routine Measurements' tab to be `rcpch-red`, clearly pink is being inherited:

<img width="1312" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/0e246f5f-fff2-4a91-8347-c53d985daee3">

And here is the call structure for the computed layout:

<img width="602" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/717270a9-b333-4d10-add0-68214d421dce">

Where apparently from the CDN, Tailwind is setting an important tag to the background colour set whenever a tab is marked as 'checked'.  Even by setting `!bg-rcpch-red` in the html myself, pink seems to still be inherited.

Am I correct in thinking that by introducing a build step we could solve this problem by being able to customise the tailwind config @mbarton ?

**Comment by eatyourpeas** [comment]
now fixed with #237
