### ISSUE TITLE
Visit forms not properly re-rendering after resubmission

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#124]
[After dev team discussion]

For a visit that a user would like to update, it seems that resubmitting the form clears some of the values stored in the form. It is possible that this is due to tags not having 'value' attributes

**Comment by dc2007git** [comment]
Note - after testing with @anchit-chandran it seems like the Visit form has this property only when all errors are not resolved. I.e. , if a form has errors and you resolve all errors, then submit, there are no issues and the updated visit saves. But, if you do not resolve all errors in a visit then the visit will clear its data from the tags of type date and select for some reason

**Comment by mbarton** [comment]
Fixed in common code as part of #168

**Comment by mbarton** [comment]
No it's not 😆
