### ISSUE TITLE
Adding patient error

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#128]
When working directly in development (even after having nuked the docker volumes and restarted the containers) I get this error when I add a patient.

Here is some example behaviour - after creating superuser, if I were to add a patient manually through the form, this works fine. then I can add patients via the csv method. Any patient I try to add manually after this throws the error shown below (of course using dummy data). Any ideas what could be causing this issue @eatyourpeas? maybe a discrepancy between the migrations and what is being added into the table with the form?:

<img width="870" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/6ee0572e-b2e0-458c-a993-12e2c9e1a57e">

**Comment by mbarton** [comment]
I get a different error now:

![Screenshot 2024-07-09 10 06 12](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/395805/1ff3a98a-7ce2-42d4-85f4-88ee4cbfd663)
![Screenshot 2024-07-09 10 06 30](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/395805/a055aa7d-80bc-4dff-81e2-34bae1ff2fb9)
