### ISSUE TITLE
Data model review

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#132]
is `npda_user.organisation_employer` == `ods_code` specifically? If so, was thinking we should rename this, as could have confusion between that and just e.g. organisation name

**Comment by eatyourpeas** [comment]
ODS code is better than organisation name because that has a tendency to change over time, where as the code does not. We currently use the code to look up the organisation details from the our API and that in turn tells us which PDU they are part of.

**Comment by anchit-chandran** [comment]
Yep agreed - could we change the field name to e.g. `organisation_ods_code`? Better to do so earlier rather than later

**Comment by mbarton** [comment]
Closing as there's an entire OrganisationEmployer model that NPDAUser refers to
