### ISSUE TITLE
Calculations for the data completeness report

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/national-paediatric-diabetes-audit#137]
Here are the calculations for the DCR (data completeness report) - let me know if anything's unclear.

**Comment by AmaniKrayemRCPCH** [comment]
[Calculations_AK_20240621.xlsx](https://github.com/user-attachments/files/15927723/Calculations_AK_20240621.xlsx)

**Comment by mbarton** [comment]
Dupe of #88
