### ISSUE TITLE
Inclusion of Jersey

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/national-paediatric-diabetes-audit#138]
Jersey has now been added to the audit - they're not part of traditional NHS structures. 

The hospital in Jersey is Jersey General Hospital - we've assigned it PDU no. PZ248

Address: The Parade, St Helier, Jersey JE1 3QS, Jersey
Trust - N/A
ICB - N/A
Network - N/A
NHSE Region - N/A
Country - Jersey

**Comment by AmaniKrayemRCPCH** [comment]
Jersey has its own index of deprivation. We need to consider how we calculate this

**Comment by eatyourpeas** [comment]
RCPCH NHS Organisations API now has Jersey in it so can now pull through to NPDA
