### ISSUE TITLE
Figma Design

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#140]
Edit link: https://www.figma.com/design/ejgejj2H1f7LNmHTpu2XDo/NPDA?node-id=0-1&t=n2hbvYkSfHHBJ4bB-1 

Figma design for the application.

**Comment by dc2007git** [comment]
Thanks for this @anchit-chandran. Have moved the figma link into the readme so it's accessible from the repo homepage instead of from Issues, just to separate concerns and keep things a bit tidier in the repo.
