### ISSUE TITLE
Automatically calculate index of deprivation for Jersey

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#142]
Jersey has its own index of deprivation. We need to consider how we calculate this

_Originally posted by @AmaniKrayemRCPCH in https://github.com/rcpch/national-paediatric-diabetes-audit/issues/138#issuecomment-2182660539_

**Comment by mbarton** [comment]
Sprint meeting 23/08/24 - @AmaniKrayemRCPCH to review how we could do this

**Comment by mbarton** [comment]
Sprint Meeting 06/09/24 - agreed we're not going to do this for Jersey as they don't have a big enough population to do statistically robust analysis for this metric
