### ISSUE TITLE
is_staff chekcbox on NPDAUser form consideration

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#146]
the is_staff button is to assign the privilege to a user to be able to access the django admin. However, considering that it is users of type Coordinator and the RCPCH audit team who will be utilising the NPDAUser form, and thus assigning these privileges, we should potentially remove/rename this box because it could lead to confusion. 

'Is the user I'm adding a member of staff at the hospital? Yes, so tick `is_staff`' - might be the kind of thought process giving our users accidental access to the django admin!

**Comment by eatyourpeas** [comment]
agreed. possibly a nice option for only superusers to be able to see
I have added an implementation in your branch to hide those elements in the template.
