### ISSUE TITLE
Logging in staff from RCPCH

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#154]
The RCPCH has its own ods code, and as such users can be added to this organisation - however we need to decide how this will work in the scope of PDU registration for users that are assigned to this organisation

**Comment by mbarton** [comment]
I think we should use it as a test organisation so you’d still need to be a separate user group to be an administrator who can see all of them

**Comment by mbarton** [comment]
We have a PZ code for RCPCH users within the app - `PZ999`
