### ISSUE TITLE
Changing PDU doesn't work

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#160]
I don't think the [logic in patient.py](https://github.com/rcpch/national-paediatric-diabetes-audit/blame/development/project/npda/views/patient.py#L135) was updated after we refactored [PDUs to be a dataclass](https://github.com/rcpch/national-paediatric-diabetes-audit/commit/7898c16bc663ce5ecf9b3bb757704ad5017342c7#diff-34fe42c3b6b40124852d1048148d6699fc0f28ca64f1c47b6610b2c49bdce481)

![Screenshot 2024-07-09 10 11 04](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/395805/aaffcfac-2656-45dc-883e-1023da2f1a6f)

![Screenshot 2024-07-09 10 11 28](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/395805/16805208-3f4b-49ce-ab20-93647f827ffa)

**Comment by mbarton** [comment]
Pages still load as it's only the PDU switching code that calls functions from `pdu.py` returning dataclasses. The session setup on initial login calls `get_single_pdu_from_ods_code` which returns plain JSON.

You can't `json.dumps` a dataclass so we will need to think about how to approach this. @anchit-chandran I will try and catch up with you to understand why we changed the implementations in `pdu.py`.

**Comment by anchit-chandran** [comment]
Added dataclasses to essentially get object typing on the returns from the external API. Can add methods to fix this, I must have missed
