### ISSUE TITLE
Missing GP information in new patient form causes a full screen error

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#163]
It really should be a form validation error as we already do for an invalid postcode

**Comment by eatyourpeas** [comment]
I think the work flow for GP ods code is not tied down. Currently the users are told to look up the GP ods code as a field to submit on their CSV. I was going to suggest we only require the postcode ( not currently a field) and we use that to look up the odds code. Equally, is the odds code is provided, we don't need the postcode or any look ups

None of this is yet implemented.

**Comment by mbarton** [comment]
@eatyourpeas agreed it's not tied down - #166 at least surfaces the errors inline. At the moment it would be a big angry blank screen for users since the `ValidationError` isn't caught from `Patient.save`
