### ISSUE TITLE
move tooltip positioning as covering npda user id in user table

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#170]
Annoyingly the tooltip covers the link to click into a user via their ID. 

![Image](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/68898006/b74dbfc0-7a7c-4f00-a3a1-5e94f16a0d2d)

Fixed in the `perm-tests` branch:

![Image](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/68898006/77cf2989-db69-4ff9-b674-79ff0b18e7e5)

**Comment by mbarton** [comment]
Would https://github.com/rcpch/national-paediatric-diabetes-audit/issues/150 help here?

**Comment by mbarton** [comment]
Not sure what fixed this but the tooltip is now fully to the right
