### ISSUE TITLE
Edit in particular audit year

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#204]
- Allow NPDA team to set which quarters are open for submission (can be through Django admin)
  - There can be a grace period for late submissions

**Comment by eatyourpeas** [comment]
As per sprint 9/8/24
Submissions to be accepted across the whole audit year. Only one submission per year - each new one to overwrite the previous.
Quarters to be shown in the reporting, possibly in the visit table, but do not need to create a submission for each quarter, only one for each year.

**Comment by mbarton** [comment]
We can derive year and quarter from the visit dates themselves
