### ISSUE TITLE
Patients assigned to incorrect AuditCohort

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#215]
1. Clear all data in the database (`s/DELETE-LOCAL-DATA`)
2. Create a new superuser (`s/create-superuser`)
3. Log in as that user
4. Create a patient in one PDU using the UI
5. Create a patient in another PDU

**Expected**: the second patient is assigned to an AuditCohort for the second PDU
**Actual**: they're assigned to the AuditCohort for the first patient

This logic is incorrect and does not filter to the correct PDU and organisation:

https://github.com/rcpch/national-paediatric-diabetes-audit/blob/a3c0170144134d3347bc4a7d67f844fcd42fc02b/project/npda/views/patient.py#L196

**Comment by mbarton** [comment]
The UI still filters patients correctly as we filter using the `Site` model not the `AuditCohort` here:

https://github.com/rcpch/national-paediatric-diabetes-audit/blob/a3c0170144134d3347bc4a7d67f844fcd42fc02b/project/npda/views/patient.py#L59

**Comment by eatyourpeas** [comment]
This is actually now fixed since the refactor of AuditCohort to Submission. I will add this situation to the list of tests
