### ISSUE TITLE
Add csv upload tests

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#220]

**Comment by mbarton** [comment]
Riffing off the top of my head but I think the following tests are worth prioritising:

- all rows valid
- some rows missing a required field so don’t save
- some rows have a validation error but save anyway
- a patient with multiple visits

and I guess its worth having those tests for both the fields that end up on Patient and those on Visit.

We definitely shouldn’t aim for comprehensive test coverage of all validation rules as after #31 we’d be essentially testing a lot of Django Forms and not our own code.

I would suggest we add tests for anything unexpected or regressions as we go along though.
