### ISSUE TITLE
request account

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#23]
This feature does not exist within E12, but could be considered for NPDA
In the dropdown below login, a link could lead to a form to request an account from the NPDA team - either by email or as an in-platform request.
For discussion with the NPDA team

**Comment by mbarton** [comment]
We won't do this in the first instance. It can cause unnecessary work for the RCPCH audit team as they have to respond to the query by bugging the lead who can approve the request
