### ISSUE TITLE
move validations out of forms into `validators.py`

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#240]
For the moment it is fine to have all field validations coded into the `clean_` functions in the forms, but once we start using the rest framework, that same validation logic will be needed here also.

We should therefore abstract the validation logic into their own `validators.py`, eg:
```python
# validators.py
from django.core.exceptions import ValidationError

SMOKING_STATUS = [
    ('Non-smoker', 'Non-smoker'),
    ('Smoker', 'Smoker'),
    # Add other statuses as needed
]

def validate_smoking_status(value):
    smoking_status_dict = dict(SMOKING_STATUS)
    if value not in smoking_status_dict:
        options = str(SMOKING_STATUS).strip("[]").replace(")", "").replace("(", "")
        raise ValidationError(
            f"Invalid value for 'Smoking Status'. Please select one of {options}."
        )
    return value
```

and this can then be called either from the form or the API serializer:

```python
# forms.py
from django import forms
from .models import Visit
from .validators import validate_smoking_status

class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial', {})
        self.patient = initial.get("patient")
        super(VisitForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            initial_value = self.initial.get(field_name)
            print(f"Field name: {field_name}, Initial value: {initial_value}")
            model_field = Visit._meta.get_field(field_name)
            if hasattr(model_field, "category"):
                field.category = model_field.category

    def clean_smoking_status(self):
        data = self.cleaned_data["smoking_status"]
        return validate_smoking_status(data)
```
or 

```python
# serializers.py
from rest_framework import serializers
from .models import Visit
from .validators import validate_smoking_status

class VisitSerializer(serializers.ModelSerializer):
    class Meta:
        model = Visit
        fields = '__all__'

    def validate_smoking_status(self, value):
        return validate_smoking_status(value)
```

**Comment by mbarton** [comment]
Asking from pure ignorance but could the rest framework use the form for validation as we do for CSV upload?

**Comment by eatyourpeas** [comment]
I think so, but I am not sure it is the way to go. The rest framework is an offshoot of django and the design approach of the framework is to match django. So in django where you have model view/controller form (template), in drf you have model viewset serializer. The serializer is analagous to the form, but the classes automate all the serialization/deserialization stuff and, depending on which type you use, some of the interfacing with the models. For simple serializers, like simple forms, where all the fields you return are the same as the fields in the model, I think you could do as you suggest. If you are returning more complicated objects (where related models or custom fields are involved for example) it might get confusing. This way (if you agree) we separate the concerns of the API from the forms, but share the logic between the two.

**Comment by mbarton** [comment]
Sounds good. I'm not wedded to a particular solution so long as it reasonably avoids duplicate validators and is as intuitive as possible to add/update/remove them

**Comment by mbarton** [comment]
We could consider validating everything using Django Rest Framework serializers again with something like [adrf](https://github.com/em1208/adrf) to let us implement the async (eg postcode) validation

**Comment by mbarton** [comment]
Closing this via https://github.com/rcpch/national-paediatric-diabetes-audit/pull/277.

I have retained Django ValidationError as the base error type so it doesn't matter whether we raise the error in our code or if Django does from framework code.

The validators stay on `PatientForm` for now - we will refactor them out as and when needed
