### ISSUE TITLE
handle case where PDU does not exist in csv_upload

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#249]
```
    # TODO MRB: handle case where PDU does not exist
```

https://github.com/rcpch/national-paediatric-diabetes-audit/blob/d986cb964894bc360ae1c11075e33767401e42ea/project/npda/general_functions/csv_upload.py#L53

**Comment by mbarton** [comment]
Blocked on #250

**Comment by mbarton** [comment]
@eatyourpeas I guess we don't need this now we seed PDUs in the startup scripts?

**Comment by eatyourpeas** [comment]
Yes I thikn it is a very theoretical error as should never really happen. Maybe we could just put in a try except and return a message in the UI to say unsuccessful and an error log so we can troubleshoot in future if it happens?

**Comment by mbarton** [comment]
Let’s leave it as an unhandled exception - we’ll still see that in production
