### ISSUE TITLE
emails still say epilepsy12 in the header

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#253]
Should read National Paediatric Diabetes Audit

@AmaniKrayemRCPCH : please change the wording of the emails that go out for account creation

**Comment by mbarton** [comment]
I'll need to set this up with @ollyrice in Sendgrid when he's back next week

**Comment by eatyourpeas** [comment]
this looks to be fixed already. Please reopen if anyone finds an email where this is not true
