### ISSUE TITLE
CSV upload success/failure table

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#26]
Once a CSV has been uploaded, those records that have been successfully validated will appear in the visits table. There needs to be a table below this which summarises or details:
1. those records that could not be validated
2. the reasons those records were not validated
3. a csv download option of this list of invalid records

**Comment by mbarton** [comment]
@eatyourpeas I think we can close this since all the records end up in a new submission?
