### ISSUE TITLE
KPI definitions for 22&23 confirmation

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#268]
hey @AmaniKrayemRCPCH 

kpi definitions for 22&23 are:

![Image](https://github.com/user-attachments/assets/92368e18-3a0b-4af9-97a0-ab9665122940)

These have the word `'either'` but only specify 1 option (`option 4`). Wanted to confirm what the definition should be? We have types:

```python
GLUCOSE_MONITORING_TYPES = [
    (1, "No"),
    (2, "Flash glucose monitor"),
    (3, "Modified flash glucose monitor (e.g. with MiaoMiao, Blucon etc.)"),
    (4, "Real time continuous glucose monitor with alarms"),
    (5, "Other"),
    (99, "Unknown"),
]

```

**Comment by AmaniKrayemRCPCH** [comment]
apologies! the word 'either' shouldn't be there. only include (4, "Real time continuous glucose monitor with alarms"),

**Comment by anchit-chandran** [comment]
thanks!
