### ISSUE TITLE
KPI 24 calculation / definition query

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#269]
![Image](https://github.com/user-attachments/assets/ce64db15-1006-4b8a-823b-65b5d45d2d49)

KPI24 has

`Denominator` : `Total number of eligible patients (measure 1)`

So far, I've counted `total_eligible` as `denominator`. But in this case, `total_eligible` is the subset of `denominator` who are ALSO on an insulin pump treatment regimen - **does that sound right**?

For the numerator, it's the subset of the `total_eligible` patients who ALSO have a `closed_loop_system`.

Each KPI calculation so far outputs an answer in the following structure:

```python
total_eligible = ___
total_ineligible = ___
total_passed = ___
total_failed= ___
```

I wanted to confirm the test I've written for this calculation (which passes):

Seeded patients:

```
8 patients who are eligible KPI1 AND are on insulin pump treatment regimen
    of these, 
        6 have a closed loop system
        2 do not have a closed loop system

2 patients who are ineligible for KPI1
6 patients who are NOT on insulin pump treatment regimen
```

Expected output:
```
EXPECTED_TOTAL_ELIGIBLE = 8
EXPECTED_TOTAL_INELIGIBLE = 8
EXPECTED_TOTAL_PASSED = 6
EXPECTED_TOTAL_FAILED = 2
```

Is this correct?

**Comment by mbarton** [comment]
@AmaniKrayemRCPCH just bumping this one up your inbox :)

**Comment by AmaniKrayemRCPCH** [comment]
Thanks for the reminder. 

This looks correct to me!
