### ISSUE TITLE
denormalize user

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#276]
Currently if a user uploads a CSV, the rows in it are validated against the relevant model, errors collected of the affected fields and a record stored for each in relevant model. This works particularly for the visit model (which has no unique identifier) but not so much for the Patient model which complains if there are two instances of NHS number which currently has `unique=True` in the model.

If a user uploads the same patient in the same submission, the new csv will be saved, the old csv, patient and visit records are deleted and the new records saved. A record of the upload remains in the submission table, but it is inactive and all related csvs and patient data have been removed.

However, if someone else, in a different PDU creates a new submission which is active but contains the same patient, this will generate an error at database level (since NHS number is unique) and the submission will be saved but none of the patients.

This highlights a fundamental issue possibly about the data model and versioning of our records. One way round this would be to allow multiple records with the same NHS number in the Patient table, but not allow more than one record per Patient in the Transfer table in a given active submission. Possibly we need to chat about this.

**Comment by mbarton** [comment]
Not quite sure how to model this in the Django ORM but I think it makes sense for patients to be unique by NHS number within a given submission. The CSV upload code ensures this at the moment as it groups by NHS number before validating the patient fields but we'd probably need something for the form submission that checks it.

Allowing multiple patients this way also solves the problem of how we model a patient postcode or GP details changing over time.

**Comment by eatyourpeas** [comment]
This introduces some complexity now that I have started to think about this properly, so before going further, I would be grateful for the views of @AmaniKrayemRCPCH @richardshepherd45 @cillian-rcpch @FrancescaAnnan justin

Let me try and summarise the problem (sorry for the long post):

### Proposal
The suggestion is that **one** patient should be able to have **more than one** patient record (currently the platform is constrained to only one), but only one record that is associated with a given Paediatric Diabetes Unit. This is because in health care a patient should never have more than one GP, so when they move address, and change GP, their record will move. If we want to retain information from the previous GP and address, we would need to retain the previous record and log the date of transfer so that we know which is active and which is historical. For example, a patient moves their care from Leicester to Norwich because they have relocated, so there would be two records for that patient, each with the same NHS number but each with different addresses (and IMD score) and GP ods code. The first record would be associated with Leicester PDU, the second with Norwich PDU. The date of transfer let's say is 1st of October, midway through the audit year.

### Why might we do this?
By retaining the patient record from Leicester and the date of transfer, we can then calculate audit measures for PDU that are pro rata against the time spent there. Currently, if a PDU has failed to collect all the measures prior to transfer, the receiving PDU has an uphill struggle to get the child registered with DECS and seen, annual review done and so on before the audit year runs out, and therefore is likely to fail the audit for that child through no fault of their own.

### What does this mean for the audit submissions?
In terms of submissions, the child will have moved PDUs in the middle of an audit year, so at the time of transfer from Leicester, the audit would collect measures for Leicester PDU up until transfer date (and IMD would be calculated from their previous address), and after the transfer date measures would be collected for Norwich, including IMD. This means while calculating the measures, for that child the denominator for each needs to be pro rata based on the amount of time spent in either PDU. 

This makes this whole process quite complicated. For example, if the patient has to have 4 HbA1cs in the audit year, and only one was done while they were at Leicester but that they moved to Norwich midway through the year, Leicester would fail the measure (as pro rata they should have gathered 2 HbA1cs by the half-way point), and then Norwich is only obliged to gather 2 more for the rest of that year, rather than 3 (as it stands under the current system). Considering parts of the year in the denominator of each measure though starts getting tricky and while arguably fairer, may lead to more arguments between PDUs rather than fewer.

### What if we leave things as they are?
In this scenario there is only one patient record per NHS number. This means that at the point of transfer, the child disappears from the Leicester submission midway through the year, the address updates to Norwich and the IMD score changes. At the same time, the child appears on Norwich's list  and they become responsible for all the measures of that child for the whole year, and inherit the audit record for that year. Arguably this is easier.

### If we leave things as they are, does that still leave any problems to solve?
If we leave things as they are, we still need a way of implementing transfers. We do not necessarily need to have a complicated transfer system as we do in Epilepsy12. When the child moves PDU to Norwich they would simply appear in the Norwich submission (at whichever point in the year this happens). At this point, they would be automatically removed from Leicester's submission and added to their own. There is complexity here though - in the Norwich upload, the NHS number would be used to identify that the child already exists in another PDUs submission, and while the patient details might be updated and overwritten, we would need to keep what previous visit details were there so that those data were not lost. This process would need to continue for the rest of the audit year else any subsequent csv uploads for that patient by Norwich that did not include the Leicester visits would otherwise overwrite any previously held data on that child in that submission. The worry with this approach is that this will lead to a divergence of what is held in the platform and what is in the PDU clinical record. For example if Norwich use Twinkle, when they create a csv it will not contain any of the Leicester visit data and will overwrite any data previously submitted in that year by Leicester. I think we probably need some notification if a child does appear in a submission to say to Norwich for example 'This child is already part of a submission in Leicester. By proceeding with this submission this child will be removed from Leicester's submission and added to yours'. Or something similar. 

Currently what happens I think is that the child is transferred, occasionally with an email or phone call beforehand and a pretty bald transfer letter along the lines of 'Please accept the transfer of this child with T1DM. I copy my recent clinic letter'. I doubt the previous audit submission data is transferred with the child - certainly that is not my experience. If Norwich do not want to lose what data was previously collected in Leicester earlier in the year, we necessarily will need a workaround as suggested above. Or we could go with what currently happens, which is that the receiving PDU inherit a child with a blank record and either accept they will fail for that child for that year, or hurriedly redo all the measures before the year runs out.

I hope that makes sense.

So my questions are:
1. Is this summary correct?
2. Which option do you prefer:
- Option 1: duplicate patient records and pro rata measures for those who transfer centres
- Option 2: unique patient records which overwrite previous records if details change
3. Duplicate submission handling - are you happy with suggestion of handling transfers in the platform or should there be some other workflow? Should we retain submission data from the previous PDU to the new PDU in the case of a transfer, or just overwrite as we do with everyone?

**Comment by mbarton** [comment]
I'm worried that with option 2 it would be impossible to run reports against previous audit periods and guarantee you'll get the same data as before. I think could bite us in the future as we do more reporting in the box.

**Comment by eatyourpeas** [comment]
Thanks @mbarton - sounds good to me.

So if we go for option *one* the follow up question is:
If we allow more than one patient record with the same NHS number, should we constrain the NHS number to being unique **within a submission**, or allow more than one record with the same NHS number to exist within the same submission?

The two options here would be:

## Option 1 - unique within a submission

The Leicester child patient record (storing address) is retained for all submissions they lived there a full year, but the moment they move to Norwich, their address changes to Norwich for the whole audit year, even if they did not move there until midway through the year

## Option 2 - duplicates allowed within a submission

The Leicester child patient record is retained for submissions they lived there, including fractions of an audit year up until the transfer. This means the child would potentially have 2 submissions for the year they transferred - generating 2 deprivation scores and two sets of measures - 1/2 in a submission under Leicester, 1/2 in a submission under Norwich. If we did this when calculating the results we would need first to merge the two submissions into one and also decide what to do in situations where there are duplicates for measures (eg IMD score, or situations where the annual review was done twice that year)

**Comment by mbarton** [comment]
My memory from previous catch up meetings with @AmaniKrayemRCPCH was it was fine to do option 1 (they move for the whole year rather than pro rata) but discussions may have moved on since then.

@eatyourpeas does pursuing option 1 stop us from moving to option 2 in the future?

**Comment by eatyourpeas** [comment]
Possibly not but if we are going to do 2 i think we might need a middle table between Patient and Submission. At the moment we are using the django default M2M ORM implementation, which means you define the relationship in one of the 2 end models in the relationship (we are using Submission) and under the hood django creates a middle model between them. If we are going to have 2 submissions for a child, we possibly need to define the middle table ourselves so that we can store attributes to define the nature of the submission (eg is_primary) so that we know which to merge into which.
Also we would need to know the rules around merging submissions and incorporate all that as a step before running any calculations

Option 1 for sure is easiest. And we could put a middle model in for that anyway even if we don't use it that much
