### ISSUE TITLE
kpis 41-43 query

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#284]
wanted to confirm the denominator for KPIS 41-43 are measure 7 *(Number of patients with Type 1 diabetes who were diagnosed within the audit period)* plus additional filter of coeliac diagnosis on date that is `<= AUDIT_END_DATE - 90 days`?

Also to confirm the meaning of the notes column, does `'90 days BEFORE OR AFTER date of diagnosis'` mean a `coeliac_screening_date` 90 days before or after the `diabetes_diagnosis_date`

![Image](https://github.com/user-attachments/assets/db9b3c44-69f6-4729-aff1-c35949643206)

**Comment by AmaniKrayemRCPCH** [comment]
> wanted to confirm the denominator for KPIS 41-43 are measure 7 (Number of patients with Type 1 diabetes who were diagnosed within the audit period) plus additional filter of coeliac diagnosis on date that is <= AUDIT_END_DATE - 90 days?

For KPIs 41 and 42, the denominator is measure 7 **and** date of diagnosis is `<AUDIT_END_DATE - 90 days ` (not <=)

Apologies, the denominator for KPI 43 is measure 7 **and** date of diagnosis is `<AUDIT_END_DATE - 14 days` (14, not 90 days)

> Also to confirm the meaning of the notes column, does '90 days BEFORE OR AFTER date of diagnosis' mean a coeliac_screening_date 90 days before or after the diabetes_diagnosis_date

Yes

**Comment by anchit-chandran** [comment]
Have updated like this. If happy, can close.

To double confirm coeliac screening date, is it:

```
90 days before <= COELIAC_SCREEN_DATE <= 90 days after
```

![image](https://github.com/user-attachments/assets/cc71be5d-c8a6-423f-a89a-581a8310fa13)

**Comment by AmaniKrayemRCPCH** [comment]
Looks correct to me! @cillian-rcpch can you confirm?

**Comment by cillian-rcpch** [comment]
> Have updated like this. If happy, can close.
> 
> To double confirm coeliac screening date, is it:
> 
> ```
> 90 days before <= COELIAC_SCREEN_DATE <= 90 days after
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/68898006/370626509-cc71be5d-c8a6-423f-a89a-581a8310fa13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjAwODcsIm5iZiI6MTcyNzI1OTc4NywicGF0aCI6Ii82ODg5ODAwNi8zNzA2MjY1MDktY2M3MWJlNWQtYzhhNi00MjNmLWE4OWEtNTgxYTgzMTBmYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEwMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MzQxNmQyZmM0YTRjYWI2N2ZiNzZmNzMxNjhkYjI5ZTZhMzJkNmVmODg3ZGJjODhlNzBkNTk5OTI4NmRhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v8I5JfJUCJIqBI-NDbqwPNlF-9rZbKbL-wgxc_KkQNE)

Hi, can confirm that this is all correct. Thanks both!
