### ISSUE TITLE
KPI 44-49 Query

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#288]
Could you guys confirm all these KPI definitions are correct?

Particularly KPI 44-45 -> I don't know how to combine the calculation of mean hba1cs  with denominator of `measure 1` (just a count of patients eligible for KPI1)

![Image](https://github.com/user-attachments/assets/bfc6747b-2e6b-439e-9abf-fb8539f84ce7)

**Comment by cillian-rcpch** [comment]
Hi Anchit, 

First I want to say that there is a mistake in the screenshot you've shared. The "description" field for KPI 44 should say "the **median** for each patient is calculated. We then calculate the mean of the **medians**". Sorry, hope that doesn't set you back much.

For KPIs 44 and 45, we first calculate the median HbA1c of each patient (excluding any HbA1c measurements taken within 90 days of diagnosis). So at this point you have 1 value for each patient. We then calculate the mean (or median) HbA1c value of these median values (excluding any missings/NAs for HbA1c). 

I don't know if you know any R (sorry, my Python isn't great) but this is what it would look like in R for Type 1 with comments written after #s:

hba1c_stats <- data |> 
  filter(!is.na(HbA1c_median), diabetestype_aggregated=="Type 1") |> # filter out NA HbA1c_median values, and include only Type 1
  group_by(PDU) |> # we are interested in PDU level here
  select(HbA1c_median) |> # median of each patient, excluding any measurements taken within 90 days of diagnosis
  summarise(n=n(),
            mean = mean(HbA1c_median), 
            median = median(HbA1c_median))

Does that help?

**Comment by anchit-chandran** [comment]
Not set a setback at all dont worry, will be a quick edit

>hba1c_stats <- data |>
filter(!is.na(HbA1c_median), diabetestype_aggregated=="Type 1") |> # filter out NA HbA1c_median values, and include only Type 1
group_by(PDU) |> # we are interested in PDU level here
select(HbA1c_median) |> # median of each patient, excluding any measurements taken within 90 days of diagnosis
summarise(n=n(),
mean = mean(HbA1c_median),
median = median(HbA1c_median))

Great yep familiar with R, that is perfect and can translate. Are each of the queries already written in R? Was thinking that would be a massive help for verifying all the queries!

**Comment by cillian-rcpch** [comment]
All of the queries are written in Stata with many of them also in R. But they're all scattered around various scripts for when they are needed for our work and usually involve many intermediate variables etc., so it's not as straightforward as just sharing with you a single file that has all queries unfortunately. 

If you have any questions about any of the queries I'll try to make a useable example for you from our code that I can share (as I've done with KPIs 44-45 here), especially now that I know you're familiar with R. So feel free to just keep assigning me any issues as you've done here. Hopefully that works for you?

**Comment by anchit-chandran** [comment]
That's great cillian! Will be a massive help as calculation edge cases crop up
