### ISSUE TITLE
verbose logs

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#29]
Logging is enabled and implemented the same as E12. It is a bit verbose though - with every database backend operation logged to the console as a debug statement.
We need to:
1. agree what should be included in the logs
2. update `logging_settings.py` in project root to reflect this

**Comment by anchit-chandran** [comment]
Can set the CONSOLE_DJANGO_LOG_LEVEL="INFO" to avoid this:

```
# DJANGO LOGGING
CONSOLE_DJANGO_LOG_LEVEL="INFO" # default Django-specific console logs [DEBUG, INFO, WARNING, ERROR, CRITICAL]
CONSOLE_LOG_LEVEL="DEBUG" # Epilepsy12 App console logs [DEBUG, INFO, WARNING, ERROR, CRITICAL]
FILE_LOG_LEVEL="DEBUG" # All logs, but to file [DEBUG, INFO, WARNING, ERROR, CRITICAL]
```
