### ISSUE TITLE
Share validation functions between CSV upload and edit forms

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#31]
Allied to #24 
The API relating to to visits will need access to the validation functions used in the csv_upload

**Comment by mbarton** [comment]
We should be able to re-use the `PatientForm` and `VisitForm`, manually binding data from the CSV row, call `.clean()` and check `errors` on the form.

We'll need to implement #47 to collect all the errors in one go rather than raising exceptions.

**Comment by mbarton** [comment]
Both CSV upload and form submission now use the same validation code. When we introduce an API in the future we'll need to look at this again, although the shortest route to something usable is probably to submit the existing form behind the scenes in the API as we do with CSV upload
