### ISSUE TITLE
User Permission Levels

### ISSUE THREAD

**Issue by richardshepherd45** [rcpch/national-paediatric-diabetes-audit#313]
Not sure what RCPCH Audit Children family is supposed to be and there is no Admin level user. We need Administrator, Coordinator, Editor, Reader RCPCH Audit Team

**Comment by eatyourpeas** [comment]
Thank you @richardshepherd45  - super grateful for all the feedback.There is documentation on this - I will post the link as soon as it it fixed.
The Children and Families group is planned to be removed but the idea was to have provision for child/family access for consent purposes in future. We built into E12 the option in future for families to have logins to view their children's data and give or remove their consent for participation. The other categories are as you list, though I am not clear how admin is different from RCPCH Audit Team. Previous discussion on this which @AmaniKrayemRCPCH signed off was that we would avoid the word administrator - see conversation [here](https://github.com/rcpch/national-paediatric-diabetes-audit/issues/134)

**Comment by AmaniKrayemRCPCH** [comment]
Apologies for the confusion! I believe it should be:

- Coordinator (= administrator on Netsolving)
- Editor (= editor on Netsolving)
- Reader (= reader on netsolving)
- RCPCH Audit Team (that's us! some of us will also be superusers).

Is that ok?

**Comment by mbarton** [comment]
Yep that's what we have implemented. Thanks!
