### ISSUE TITLE
Publish documentation to live

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#323]
Some options off the top of my head:

1) Publish it on GitHub pages using a subdomain
2) Publish it on GitHub pages and embed as an iframe in the main app
3) Copy it as static files into the main app and serve with WhiteNoise (as we do with E12)

I prefer 1 or 2, 3 was only really done in a panic as I completely forgot about the docs when migrating to Azure Container Apps.

Any preference @eatyourpeas @anchit-chandran?

**Comment by eatyourpeas** [comment]
I vote for GitHub pages as a subdomain

**Comment by anchit-chandran** [comment]
1! 

DIdn't know we directly serve the docs in E12, that's cool but think it's only worth later
