### ISSUE TITLE
Create data generator for csv

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#328]
Following csv values in `dummy_sheet_invalid.csv` differ from data model. How to map datamodel values to csv values @eatyourpeas ? Particularly `null` values (will be blank in resulting csv)

# True / False fields

LEFT=our data model's value (thus the data generator value which outputs into csv) (enums)
RIGHT = current value of the `dummy_sheet_invalid.csv` (generally just true / false)

`glucose_monitoring`
![Image](https://github.com/user-attachments/assets/96ed3678-194e-445d-b17c-4214e058578f)

`thyroid_treatment_status`
![Image](https://github.com/user-attachments/assets/ddf7e087-cbd2-4be7-8068-0eb1b2203b6b)

`gluten_free_diet`
![Image](https://github.com/user-attachments/assets/2a93d776-af5a-4242-851c-9e623d8d0cc5)

`psychological_additional_support_status`
![Image](https://github.com/user-attachments/assets/af383dff-42e8-49a3-b9bf-b4dd60703cb0)

All `YES_NO_UNKNOWN`:

`smoking_status`
Does the patient smoke?

`dietician_additional_appointment_offered`
Was the patient offered an additional appointment with a paediatric dietitian?

`verbose_name`
Was the patient using (or trained to use) blood ketone testing equipment at time of visit?

# `nan` becomes float

Pandas will cast `nan` columns to float. This means resulting csv columns with nans can either:

1. Have blank values, but the existing values are floats so e.g. an enum of `[1,2,99]` becomes `[1.0, 2.0, 99.0]`
2. We specify an int value to fill in for `nan`, so all rows have value

**Comment by eatyourpeas** [comment]
Pandas is doing something we do not want. The numbers in the choices are the keys and values are the text passed to us by NPDA. These choices are used in the models to store the results. The keys are all integers but null is allowed, and blank in forms is allowed, as some measures are only captured once a year (eg coeliac)
