### ISSUE TITLE
Replace findthatpostcode with our own self-hosted postcodes.io

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#342]
We have noticed variable performance on findthatpostcode.uk, sometimes up to 10 seconds for a single request. This is fine because we are of course not paying for it! However in practice that's likely to be too slow for our users.

We have discussed creating a self-hosted instance of [postcodes.io](https://postcodes.io/). We moved away from that provider in E12 as it seemed less up to date than findthatpostcode but since then they have made multiple releases and should now be up to date as of August 2024.

It's now up and running at https://api.rcpch.ac.uk/postcodes (API key required).

We will migrate in two steps

1. Create new settings that when set use our postcodes.io
2. Remove the old findthatpostcode code path

That way we're rollback safe and won't immediately break everyones local dev environments

**Comment by eatyourpeas** [comment]
I think this is now done
