### ISSUE TITLE
Handle CSV upload missing headers

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#348]
Some users upload CSV files without headers. We would have to assume they're following the template and parse accordingly

@AmaniKrayemRCPCH to confirm how many users do this

**Comment by eatyourpeas** [comment]
That feels to me a bit too permissive. I don't think it is too much to ask for clinicians/admin to provide the data in the requested format. We are stripping spaces etc if the headings have these sorts of invisible errors but the documentation for submission is good and has been in place a long time. 
My vote is to reject the whole csv at the point of upload if the basic data types are not correct with a polite message to check their working and try again. This would include providing the header names in the requested format, given that if the data are provided with the columns in a different order, without the column headings, we would have no idea which column was which.

**Comment by eatyourpeas** [comment]
I have implemented this btw in #368 but very simple to undo if people prefer

**Comment by AmaniKrayemRCPCH** [comment]
Just following on to note that we want to reject submissions without a header row. Thanks!
