### ISSUE TITLE
download csv/xls buttons

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#377]
On reflection the wording for the buttons is not quite right.
The left hand button needs to convey that this allows download of the .xls which has the orginal submission + summary pages, the right hand downloads the original submission in its original format.

Perhaps the buttons need download icons with a tooltip to explain more clearly what each one does?

**Comment by reecehill** [comment]
For reference:
![image](https://github.com/user-attachments/assets/8d381c3f-b4ba-41e0-a7b0-9c11a855883a)
(On invalid CSV submission)
