### ISSUE TITLE
Clicking logo and 'home' icons seem to take you to un-obvious places

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#382]
![Image](https://github.com/user-attachments/assets/d99282d8-3df3-4c59-9062-cc7c97a58490)

currently logo takes you to `/home` and home icon takes you to `/dashboard`

I'd expect clicking the logo to take me to `/home` and/or the home icon to take me to the same place.

Going to change the home icon to same as the other nav links, to `Dashbord` if that's okay @eatyourpeas ? Like this

![Image](https://github.com/user-attachments/assets/0e848fd3-6986-40c2-80af-cf530db88e5f)

**Comment by reecehill** [comment]
I agree - the destinations are not intuitive; but, I think this could/should go further.

- `/home` is also "Upload CSV" -> for some users, the same link appears twice in the navbar.

- `/dashboard` actually is the KPI table/report.

Typically, /home pages serve as landing pages: above-the-fold content, click-to-actions, brief overview of functionality, links to documentations, tutorials etc. 
Whilst /dashboard pages usually present user status, activity logs, summarised reports, statistics etc.
At present, neither of our pages meet these user expectations.

Maybe the above should be saved for a later iteration, but I definitely agree - the distinction between dashboard and home (URL wise) is unclear.

**Comment by reecehill** [comment]
Also see: #374

**Comment by eatyourpeas** [comment]
Remember that those who upload CSV should not see the questionnaire link,
and those that use the questionnaire she not CE the upload CSV link.
Superusers can see both. That was why I suggested using the dashboard as
the landing page

**Comment by anchit-chandran** [comment]
We could plan out the design on figma +/- site map https://www.figma.com/design/ejgejj2H1f7LNmHTpu2XDo/NPDA

**Comment by eatyourpeas** [comment]
linked to #390

**Comment by anchit-chandran** [comment]
@reecehill could you mock out the home page / upload page as per @eatyourpeas comments?
