### ISSUE TITLE
Extend 7 key care processes to show for all pts in a given pdu

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#383]
Make this for multiple patients![Image](https://github.com/user-attachments/assets/df566133-c02c-4548-82ae-c232a013271d)

**Comment by eatyourpeas** [comment]
This looks nice
This might be something to ask @AmaniKrayemRCPCH 
A list of 150 patients like this might look a bit crowded but I think people would find it helpful to see at a glance who is failing on what measure. We could possibly produce a summary table for the dashboard perhaps comparing subcategories such as those on closed loop, those with t2dm, perhaps with some grey columns ordered by imd, ethnicity etc

**Comment by anchit-chandran** [comment]
Will close this issue as already being discussed in #386
