### ISSUE TITLE
Dashboard content

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/national-paediatric-diabetes-audit#386]
Started sketching out the dashboard - what sorts of things do you think would be useful to have on here? (e12 dashboard on right for reference)

feel free to edit yourself too! https://www.figma.com/design/ejgejj2H1f7LNmHTpu2XDo/NPDA?node-id=0-1&t=EZnqAZk7xecWxozj-1

![Image](https://github.com/user-attachments/assets/232593c7-285e-4d43-80df-49a455387447)

**Comment by eatyourpeas** [comment]
This is a question really for @AmaniKrayemRCPCH who was going to think about this after last sprint

**Comment by anchit-chandran** [comment]
Hey @AmaniKrayemRCPCH (+/- @cillian-rcpch ) happy to do a 30-60 min call to quickly sketch stuff down for this (rough https://www.tldraw.com/), then can get onto figma to confirm with @eatyourpeas ?

Free today or fri any time after 2pm

**Comment by eatyourpeas** [comment]
allied to #390 @orangepeel73 @FrancescaAnnan views very welcome

**Comment by anchit-chandran** [comment]
rough sketch https://www.tldraw.com/r/VGHyHqb0FRZ9RyUKXEL7m?d=v344.583.854.465.page

will work on getting this onto figma for week today!

**Comment by anchit-chandran** [comment]
@eatyourpeas @AmaniKrayemRCPCH @cillian-rcpch @richardshepherd45 check first draft of dashbaord on the figma!

we should choose a different colour scheme from the pink, blue, grey as get into issues when we use it for `Sex`

![Image](https://github.com/user-attachments/assets/db1bdec4-97ff-46bd-9971-e5fb79dc3418)

**Comment by AmaniKrayemRCPCH** [comment]
Looks great! A few notes

1. I'll need to get some thoughts on if the dashboard has only the unit's data or if it includes benchmarking against region/network/national. In December, I'll run this past our methodology and dataset group. I'll also ask HQIP. 
2. And for the pictograms under patient characteristics, is it possible to also show total numbers?
3. And under HbA1c, i presume you want to show mean and median?
4. For admissions, the values should be 'Total' and 'DKA'. I don't think we want to calculate DKA at diagnosis within the dashboard.

**Comment by anchit-chandran** [comment]
Sure will make those changes!

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH made those updates inc:

- have moved the different levels of abstraction graph off to the side if we want it, for now, made all charts just pdu specific
- put x axes onto the charts from the kpi definitions, lmk if any need adjusting

also FYI on figma you can leave comments directly on different parts by using this icon at bottom (see screenshot below)! might be easier to specify and can also track progress as I can 'check' them off as they're completed

![Image](https://github.com/user-attachments/assets/2274afaf-33ac-4edf-a830-b6cc22d23c46)
