### ISSUE TITLE
dGC API not called when visits added using questionnaire

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#401]
I think this is an oversight rather than deliberate @eatyourpeas?

**Comment by eatyourpeas** [comment]
oops...

**Comment by reecehill** [comment]
Is this issue related to:
![image](https://github.com/user-attachments/assets/c6fe67fa-ff94-4d98-96dc-d51cba95a9fe)

On upload of a valid csv?

**Comment by mbarton** [comment]
That one was just the values in the dummy sheet, fixed in https://github.com/rcpch/national-paediatric-diabetes-audit/pull/400
