### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/national-paediatric-diabetes-audit#403]
using in Edge dark mode means some elements aren't visible 

![Image](https://github.com/user-attachments/assets/f1de5531-3041-480c-9069-5b335698a05c)

whoops! accidentally added this to E12.

**Comment by mbarton** [comment]
@reecehill I have a memory we considered removing dark mode entirely?

**Comment by eatyourpeas** [comment]
wrong repository. I will redirect this to NPDA

**Comment by reecehill** [comment]
> @reecehill I have a memory we considered removing dark mode entirely?

I'd used css to hide the toggle to switch between modes, thinking that would be sufficient. I suspect on some browsers the system's theme is being used as a default. 

Therefore, there is a need to remove compatibility with dark mode altogether. I'll get this sorted.

**Comment by AmaniKrayemRCPCH** [comment]
Yep, to confirm my settings are set as the below:

![image](https://github.com/user-attachments/assets/a288439b-0a15-49d6-b7da-d19ba95e71bb)
