### ISSUE TITLE
Test factories and seeding

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#43]
Factories cannot be fully implemented until inclusion of the Site and Organisation models.
Once these are in place, factories need completing to:
1. seed NPDAUsers
2. seed Patients and Visits that depend on them

**Comment by eatyourpeas** [comment]
The Site model is now implemented so we are now ready for tests: @anchit-chandran interested?

The first important tests are for:
1. user creation - who can do this, who cannot. Are users created in the correct PDU
2. user listview - who can see this, is it appropriately scoped to all users in a given PDU
3. user delete - who can do this
4. Password reset

**Comment by anchit-chandran** [comment]
Will do these

**Comment by anchit-chandran** [comment]
Do we have a md table similar to E12 docs re appropriate perms?

**Comment by mbarton** [comment]
> Do we have a md table similar to E12 docs re appropriate perms?

@anchit-chandran I believe it's here: https://github.com/rcpch/national-paediatric-diabetes-audit/blob/development/documentation/docs/developer/users.md#permissions

**Comment by anchit-chandran** [comment]
on hold whilst still building / finalising views + user flow

**Comment by anchit-chandran** [comment]
going to close this issue as the factories and seeding have been implemented. Can have a new issue specifically for tests
