### ISSUE TITLE
view_preference filter now covers the dashboard PDU name

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#435]
**before:**

<img width="1878" alt="image" src="https://github.com/user-attachments/assets/a65c4aa0-bb0a-4198-9258-adab4f1a7adf" />

**after:**

<img width="1877" alt="image" src="https://github.com/user-attachments/assets/8c018815-6fdb-4e4f-8320-a7e09b911360" />

**Comment by eatyourpeas** [comment]
I think maybe i forgot this element closes...

**Comment by anchit-chandran** [comment]
<img width="1290" alt="Image" src="https://github.com/user-attachments/assets/8a529051-21f0-436b-ad5f-00c8b460aa9c" />

fyi updated to modal, hidden behind `is_superuser` for now in case we're not allowing changing audit year etc? can update though
