### ISSUE TITLE
New patient form validation errors

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#47]
When going through the patient form, submitting an empty list produces (as expected) "This field is required" errors.

Line 56 in patient_form.py begins the start of validating each field specified as below:

`        if diagnosis_date is None:
            raise ValidationError({'diagnosis_date': ["'Date of Diabetes Diagnosis' cannot be empty"]})
        
        if date_of_birth is None:
            raise ValidationError({'date_of_birth': ["'Date of Birth' cannot be empty"]})

        if diagnosis_date is not None and date_of_birth is not None:
            if diagnosis_date < date_of_birth:
                raise ValidationError({'diagnosis_date': ["'Date of Diabetes Diagnosis' cannot be before 'Date of Birth'"]})
        
        if death_date is not None and date_of_birth is not None:
            if death_date < date_of_birth:
                raise ValidationError({'death_date': ["'Death Date' cannot be before 'Date of Birth'"]})
        
        if death_date is not None and diagnosis_date is not None:
            if death_date < diagnosis_date:
                raise ValidationError({'death_date': ["'Death Date' cannot be before 'Date of Diabetes Diagnosis'"]})`

The form then produces an error if date_of_birth or diagnosis_date is empty. But ValidationError is an Exception so will exit the function when the first conditional in the validation sequence is logged. This means that other all errors would not be listed. 

Just a small aside - we probably don't need the two first conditionals as django will produce a "This field is required" error if their conditions are met, so we'd double up on error messages!

**Comment by eatyourpeas** [comment]
Absolutely right @dc2007git good spot. Django can accept multiple fields to the ValidationError class, so we could collect these up and raise at the end of all the conditionals? Would you be happy to look at and put in a PR?
