### ISSUE TITLE
Category referencing in Visit model

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#50]
In the new Visit model as part of the daisy/tailwind branch, it would be tidier to reference the categories directly from the VisitCategories enumeration, so if we have to change a category we only have to do it in one place

**Comment by eatyourpeas** [comment]
In follow up to this also agreed. We should have top level categories to match those in NPDA [here](https://www.rcpch.ac.uk/sites/default/files/2024-02/npda_dataset_2021_guidance_updated_feb_2024.pdf) already which include:
- Patient Details
- Routine Measurements
- Annual Review/Diagnosis
- Inpatient Entry
These top-level categories could form menu items and then the categories themselves could retain the colours as agreed.
