### ISSUE TITLE
visit form design and style

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#6]
The visit form is currently long and complex
It has been broken into categories and it would be good if each of these were broken into partials to render in tabs or with some sort of single page navigation so that users have less clutter on the screen.
<img width="1341" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/1058647/b11c2e8a-b0f8-40ef-b64d-3e18480bd8df">

**Comment by eatyourpeas** [comment]
Just as an aside here. To complete this issue 2 further items need to complete:
- [ ] NPDA team need to sign off the concept of categories
- [ ] The Dev team need to decide whether it would be better to include HTMX in this view to make this form a little more reactive and easier to fill

**Comment by mbarton** [comment]
I think it's fair to call this closed and we'll raise separate issues for further work
