### ISSUE TITLE
Pre-loading date into date fields causes that category to appear as 'addressed' in the Patient Visits section

### ISSUE THREAD

**Issue by dc2007git** [rcpch/national-paediatric-diabetes-audit#60]
The new feature in #48 where we preload the date fields into the form as today is causing that category to be listed as 'addressed' in the patients visit section like so:

<img width="922" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/8a0c0e77-6acd-477e-9dc2-a38ab5ceb30c">

**Comment by eatyourpeas** [comment]
Perhaps the way out of this is not to preload the date into the field directly, but have a custom button which suggests the date to the user and this updates the field on click, so resolving the problem. Perhaps there could be two buttons - one for the date of the visit, the other for today.
