### ISSUE TITLE
component styles

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#8]
We are currently using tailwindcss and have a small number of reusable components (buttons, dropdowns, labels)
Classes are so far all within the div attributes but would be good to have a library of these for reuse.

**Comment by eatyourpeas** [comment]
conversation about this yesterday with @pacharanero and @mbarton . NPDA currently is built on tailwind and therefore the `page_elements` from E12 (which are built on semantic-ui) cannot be reused. Just to say that Tailwind currently is used as a suggestion following conversations during E12 build with most of the team saying they did not really like semantic and preferred either tailwind or bootstrap. I have therefore put tailwind in but removing and replacing with different framework would be very quick and I am super happy to be guided.
Also, we have currently a standard Django forms/views class-based implementation because htmx has not felt so essential here as it did in E12. Again, very happy to change this if review by the team of what is built already would prefer a more reactive UI. Important to mention this here, because the E12 page_elements are all written to accept parameters for the htmx attributes, so another reason they are not reused currently.

**Comment by eatyourpeas** [comment]
Decision from sprint 25/4/24 - although no definitive decision to go with tailwind, @dc2007git will explore this option and possible integration with [DaisyUI](https://daisyui.com/)

**Comment by mbarton** [comment]
@eatyourpeas @dc2007git is it still fair to say we're sticking with Tailwind now so this issue can be closed or split into smaller issues?

**Comment by dc2007git** [comment]
@mbarton happy to close this as we've decided we're moving forward with Tailwind!
