### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#9]
there is no good datepicker widget and the ones that exist tend to be in js
It would be good to create and componentize a nice datepicker as there are multiple fields that use them.

**Comment by mbarton** [comment]
What would we need above what the native [\<input type="date"\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) gives us?

**Comment by eatyourpeas** [comment]
The native one is just an input with d/m/yyy - not really a date picker. I thought it might be nice to build one with tailwind and then add that class in the form class.

**Comment by mbarton** [comment]
> The native one is just an input with d/m/yyy - not really a date picker

What specifically do we need on top of the UI that browsers render though? Each browser I've tried has some additional UI.

**Comment by eatyourpeas** [comment]
I am happy to be guided. I raised this issue because currently the django DateInput widget implements like this (in chrome).
Probably this is part of the styling issue. 
<img width="765" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/1058647/7f4d5a26-15c0-4002-b410-2545ce97aff7">

**Comment by dc2007git** [comment]
I've managed to load in a datepicker without needing any external dependencies. The only issue is that I can't figure out how to change the input format from DD-MM-YYYY. So far I've changed `DATE_INPUT_FORMATS` to `["%Y-%m-%d"]` in settings.py, and this still isn't working. Stack and the django forums haven't got any solutions that seem to be working either. Is it potentially due to the DD-MM-YYYY being hardcoded when we use the `input type='date'` tag? Here is what the code looks like so far:

```
from django import forms
from django.core.exceptions import ValidationError
from ..models import Patient
from ...constants.styles.form_styles import *
from ..general_functions import validate_postcode

class DateInput(forms.DateInput):
    input_type='date'

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = [
            "nhs_number",
            "sex",
            "date_of_birth",
            "postcode",
            "ethnicity",
            "diabetes_type",
            "diagnosis_date",
            "death_date",
            "gp_practice_ods_code",
            "gp_practice_postcode",
        ]
        widgets = {
            "nhs_number": forms.TextInput(attrs={"class": TEXT_INPUT},),
            "sex": forms.Select(attrs={"class": SELECT}),
            "date_of_birth": DateInput(attrs={'class':DATE_INPUT}),
            "postcode": forms.TextInput(attrs={"class": TEXT_INPUT}),
            "ethnicity": forms.Select(attrs={"class": SELECT}),
            "diabetes_type": forms.Select(attrs={"class": SELECT}),
            "diagnosis_date": DateInput(attrs={"class": DATE_INPUT}),
            "death_date": DateInput(attrs={"class": DATE_INPUT}),
            "gp_practice_ods_code": forms.TextInput(attrs={"class": TEXT_INPUT}),
            "gp_practice_postcode": forms.TextInput(attrs={"class": TEXT_INPUT}),
        }
```

with screenshots of the UI (I am using Chrome as well and this works well for me):

![image](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/f280060c-3d97-4b61-9aa8-7a12856f5c0d)

![image](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/65614251/1b81a521-c6ce-442c-a416-1a2569a9ac33)

**Comment by mbarton** [comment]
Hmm yeah the [info box in the MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value) says that it always displays using the locale of the browser:

![Screenshot from 2024-05-01 13-55-55](https://github.com/rcpch/national-paediatric-diabetes-audit/assets/395805/c9fa0218-3786-415a-a33c-dca4a9a610d8)

The value is normalised to `yyyy-mm-dd` before being sent to the server though so I think we're fine? Unless it would be confusing to have a different format in the UI compared to the spreadsheet

**Comment by eatyourpeas** [comment]
This was a requirement of NPDA and is set in the model. I imagine though we could change the format to be something more userfriendly, particularly if it would play nicer with our datepicker
<img width="566" alt="image" src="https://github.com/rcpch/national-paediatric-diabetes-audit/assets/1058647/8f69579f-5fdd-41ee-8868-4e034852bceb">
