### ISSUE TITLE
cohorting

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#94]
Currently filtering is scoped to Organisation, PZ Code or national. It does not filter further though to 'cohorts'. To close this issue we need to decide if we are filter against dates of data upload, or whether we will allocate cohorts to uploads.

**Comment by mbarton** [comment]
I think filtering by a submission would work?

**Comment by eatyourpeas** [comment]
this has been superceded by the concept of submissions and quarters
