### ISSUE TITLE
visit form all fields must be valid before save

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/national-paediatric-diabetes-audit#99]
Now that all the form fields are in tabs, it maybe that invalid fields are in tabs that are not active. This is nicely signposted by highlighting the tab label as red but it might be that users will not see that and try and save and be frustrated when the form is represented. 
Perhaps instead we could allow the form to save, but present a modal 'There are still some errors in [....]. Are you sure you want to save what you have done?' or something similar.

**Comment by mbarton** [comment]
Closing as you can now save an invalid visit
